force-app/main/default/objects/Assistir__c/Assistir__c.object-meta.xml
<CustomObject>
    <label>Visualização</label>
    <nameField>
        <displayFormat>Visualizção-{00000}</displayFormat>
        <label>Assistir Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visualizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assistir__c/fields/Filme__c.field-meta.xml
<CustomField>
    <fullName>Filme__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Filme</label>
    <referenceTo>Filme__c</referenceTo>
    <relationshipLabel>Visualizações</relationshipLabel>
    <relationshipName>Visualizacoes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filme__c/Filme__c.object-meta.xml
<CustomObject>
    <label>Filme</label>
    <nameField>
        <displayFormat>Filme-{00000}</displayFormat>
        <label>Filme Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filmes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filme__c/fields/DataLancamento__c.field-meta.xml
<CustomField>
    <fullName>DataLancamento__c</fullName>
    <label>Data de lançamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Filme__c/fields/ELancamento__c.field-meta.xml
<CustomField>
    <fullName>ELancamento__c</fullName>
    <formula>( TODAY() - TODAY() ) &lt; 30</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>É lançamento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Filme__c/fields/Genero__c.field-meta.xml
<CustomField>
    <fullName>Genero__c</fullName>
    <label>Gênero</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
                <label>Aventura</label>
            </value>
            <value>
                <fullName>878</fullName>
                <label>Ficção Científica</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Ação</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Drama</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Animação</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Comédia</label>
            </value>
            <value>
                <fullName>80</fullName>
                <label>Crime</label>
            </value>
            <value>
                <fullName>99</fullName>
                <label>Documentário</label>
            </value>
            <value>
                <fullName>10751</fullName>
                <label>Família</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Fantasia</label>
            </value>
            <value>
                <fullName>36</fullName>
                <label>História</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Terror</label>
            </value>
            <value>
                <fullName>10402</fullName>
                <label>Música</label>
            </value>
            <value>
                <fullName>9648</fullName>
                <label>Mistério</label>
            </value>
            <value>
                <fullName>10749</fullName>
                <label>Romance</label>
            </value>
            <value>
                <fullName>10770</fullName>
                <label>Filme TV</label>
            </value>
            <value>
                <fullName>53</fullName>
                <label>Thriller</label>
            </value>
            <value>
                <fullName>10752</fullName>
                <label>Guerra</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>Velho Oeste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Filme__c/fields/LinguaOriginal__c.field-meta.xml
<CustomField>
    <fullName>LinguaOriginal__c</fullName>
    <label>Língua Original</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en</fullName>
                <label>Inglês</label>
            </value>
            <value>
                <fullName>es</fullName>
                <label>Espanhol</label>
            </value>
            <value>
                <fullName>ja</fullName>
                <label>Japonês</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Filme__c/fields/NotaMedia__c.field-meta.xml
<CustomField>
    <fullName>NotaMedia__c</fullName>
    <label>Nota Média</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Filme__c/fields/Popularidade__c.field-meta.xml
<CustomField>
    <fullName>Popularidade__c</fullName>
    <label>Popularidade</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MoviesIntegrationIN.cls
@RestResource(urlMapping='/getMovieInteraction/*')
global with sharing class MoviesIntegrationIN {
    @HttpGet
    global static  void getMovies() {
            String userId = RestContext.request.params.get('userId');
            String userEmail = RestContext.request.params.get('userEmail');
        
            List<Assistir__c> interactions = MovieInteractionDAO.getMovieInteractionByUserIdOrEmail(userId, userEmail);
        if(interactions.size() > 0){
            List<MovieDataWrapper> movies = new List<MovieDataWrapper>();
            for(Assistir__c interaction:interactions){
                MovieDataWrapper movieData = new MovieDataWrapper();
                movieData.id = interaction.Filme__r.Id;
                movieData.name = interaction.Filme__r.Nome__c;
                movieData.description = interaction.Filme__r.Descricao__c;
                movieData.gender = interaction.Filme__r.Genero__c;
                movieData.originalLanguage = interaction.Filme__r.LinguaOriginal__c;
                movieData.averageVotes = interaction.Filme__r.NotaMedia__c;
                movieData.popularity = interaction.Filme__r.Popularidade__c;
                movieData.isRelease = interaction.Filme__r.ELancamento__c;
                movieData.releaseDate = interaction.Filme__r.DataLancamento__c;
                movies.add(movieData);
            }
            RestContext.response.addHeader('Content-Type', 'application/json');
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(movies));       
        }else{
                    
            ErrorWrapper err = getError('NOT_FOUND', 'Nenhum filme encontrado para este usuário.Certifique se o usuário é válido');
            RestContext.response.addHeader('Content-Type', 'application/json');
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(err));
        }
        
    }


    public  static ErrorWrapper getError(String errorCode, String errorMessage){
        ErrorWrapper err = new ErrorWrapper();
        err.errorCode  = errorCode;
        err.errorMessage = errorMessage;
        return err;
    }

    public class ErrorWrapper{
        public String errorCode {get;set;}
        public String errorMessage {get;set;}
    }


    public class MovieDataWrapper{
        public String  id {get;set;}
        public String name {get;set;}
        public String description {get;set;}
        public String gender {get;set;}
        public String originalLanguage {get;set;}
        public Decimal averageVotes {get;set;}
        public Decimal popularity {get;set;}
        public Boolean isRelease {get;set;}
        public Date releaseDate {get;set;}
    }
}