force-app/main/default/objects/Account/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <label>Nome</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assistir__c/Assistir__c.object-meta.xml
<CustomObject>
    <label>Visualização</label>
    <nameField>
        <displayFormat>Visualizção-{00000}</displayFormat>
        <label>Assistir Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visualizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assistir__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visualizações</relationshipLabel>
    <relationshipName>Visualizacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assistir__c/fields/Filme__c.field-meta.xml
<CustomField>
    <fullName>Filme__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Filme</label>
    <referenceTo>Filme__c</referenceTo>
    <relationshipLabel>Visualizações</relationshipLabel>
    <relationshipName>Visualizacoes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Filme__c/Filme__c.object-meta.xml
<CustomObject>
    <label>Filme</label>
    <nameField>
        <displayFormat>Filme-{00000}</displayFormat>
        <label>Filme Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filmes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filme__c/fields/DataLancamento__c.field-meta.xml
<CustomField>
    <fullName>DataLancamento__c</fullName>
    <label>Data de lançamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Filme__c/fields/Genero__c.field-meta.xml
<CustomField>
    <fullName>Genero__c</fullName>
    <label>Gênero</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
                <label>Aventura</label>
            </value>
            <value>
                <fullName>878</fullName>
                <label>Ficção Científica</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Ação</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Drama</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Animação</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Comédia</label>
            </value>
            <value>
                <fullName>80</fullName>
                <label>Crime</label>
            </value>
            <value>
                <fullName>99</fullName>
                <label>Documentário</label>
            </value>
            <value>
                <fullName>10751</fullName>
                <label>Família</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Fantasia</label>
            </value>
            <value>
                <fullName>36</fullName>
                <label>História</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Terror</label>
            </value>
            <value>
                <fullName>10402</fullName>
                <label>Música</label>
            </value>
            <value>
                <fullName>9648</fullName>
                <label>Mistério</label>
            </value>
            <value>
                <fullName>10749</fullName>
                <label>Romance</label>
            </value>
            <value>
                <fullName>10770</fullName>
                <label>Filme TV</label>
            </value>
            <value>
                <fullName>53</fullName>
                <label>Thriller</label>
            </value>
            <value>
                <fullName>10752</fullName>
                <label>Guerra</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>Velho Oeste</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Filme__c/fields/LinguaOriginal__c.field-meta.xml
<CustomField>
    <fullName>LinguaOriginal__c</fullName>
    <label>Língua Original</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en</fullName>
                <label>Inglês</label>
            </value>
            <value>
                <fullName>es</fullName>
                <label>Espanhol</label>
            </value>
            <value>
                <fullName>ja</fullName>
                <label>Japonês</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Filme__c/fields/NotaMedia__c.field-meta.xml
<CustomField>
    <fullName>NotaMedia__c</fullName>
    <label>Nota Média</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Filme__c/fields/Popularidade__c.field-meta.xml
<CustomField>
    <fullName>Popularidade__c</fullName>
    <label>Popularidade</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MoviesIntegrationINTest.cls
@isTest
private class MoviesIntegrationINTest {
    
    @isTest
    static void testGetMoviesWithInteractions() {

        Account testUser = new Account(
            Name = 'Test',
            Email__c = 'testuser@example.com'
            
        );
        insert testUser;

        Filme__c testMovie = new Filme__c(
            Nome__c = 'Test Movie',
            Descricao__c = 'Description of the movie',
            Genero__c = 'Action',
            LinguaOriginal__c = 'English',
            NotaMedia__c = 8.5,
            Popularidade__c = 90,
            DataLancamento__c = System.today()
            
        );
        insert testMovie;

        Assistir__c testInteraction = new Assistir__c(
            Account__c = testUser.Id,
            Filme__c = testMovie.Id
            
        );
        insert testInteraction;

        RestRequest req = new RestRequest();
        req.params.put('userId', testUser.Id);
        req.params.put('userEmail', testUser.Email__c);
        RestContext.request = req;

        MoviesIntegrationIN.getMovies();

    }

   
}